import Head from "next/head";
import styles from "../styles/Home.module.css";
import Logo from "../components/logo";
import { PROJECT_NAME } from "../constants/projectGenerics";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{PROJECT_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoDos.png" />
      </Head>

      <main className={styles.main}>
        <Logo />
        <h1 className={styles.title}>
          H Developments<a href="https://nextjs.org">{ PROJECT_NAME.toUpperCase()}</a>
        </h1>
      </main>
    </div>
  );
}
