import Head from "next/head";
import { PROJECT_NAME } from "../constants/projectGenerics";

export default function OtraDemo() {
  return (
    <>
      <Head>
        <title>{PROJECT_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoDos.png" />
      </Head>
      <div style={{ display: "flex", flexDirection: "column" }}>
        esto es otra pagina demo
      </div>
    </>
  );
}
